version: '3.8'

services:
  demango:
    build: .
    container_name: demango
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver --insecure 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
