# Generated by Django 4.2.16 on 2024-10-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demands',
            name='demand',
            field=models.CharField(max_length=100),
        ),
    ]
