# Generated by Django 4.2.16 on 2024-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_alter_demands_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='demands',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
