# Generated by Django 4.2.16 on 2024-10-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0003_demands_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demands',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
